/*
 * generated by Xtext 2.25.0
 */
package sh.kainz.plsql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PlsqlUiModule extends AbstractPlsqlUiModule {

	public PlsqlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
