/*
 * generated by Xtext 2.25.0
 */
package sh.kainz.plsql;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PlsqlStandaloneSetup extends PlsqlStandaloneSetupGenerated {

	public static void doSetup() {
		new PlsqlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
