/*
 * generated by Xtext 2.25.0
 */
package sh.kainz.plsql;

import org.eclipse.xtext.linking.ILinker;

import sh.kainz.plsql.linking.CustomDelegateLinker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlsqlRuntimeModule extends AbstractPlsqlRuntimeModule {

	@Override
	public Class<? extends ILinker> bindILinker() {
		return CustomDelegateLinker.class;
	}
	
	
}
