/*
 * generated by Xtext 2.25.0
 */
package sh.kainz.plsql.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class PlsqlWebModule extends AbstractPlsqlWebModule {
}
